#Application
server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:everbootpass2021@firstcluster.k6x6t.mongodb.net/bank-accounts

dbname: bank-accounts

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server2.mybluemix.net/eureka/