#Application
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:everbootpass2021@firstcluster.k6x6t.mongodb.net/clients-service

dbname: clients-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
